CREATE TABLE UNIDADES (
         ID VARCHAR(10) PRIMARY KEY,
         QUANTIDADE_FUNCIONARIOS INTEGER,
         ENDERECO_UNIDADE VARCHAR(255),
         DATA_FUNDAÇÃO DATE,
         GERENTE_UNIDADE VARCHAR(255)
)